version: 2.1
jobs:
  "format check":
    docker:
      - image: ajmasiaa/carta-backend-format-checker
    steps:
      - checkout
      - run:
          name: "checking the formatting of the carta_backend code"
          command: |
            ./scripts/checkformat.sh
      - run:
          name: "checking the copyright and licence headers in the carta_backend code"
          command: |
            ./scripts/headers.py check
  "ubuntu bionic":
    docker:
      - image: ajmasiaa/carta-backend-builder-ubuntu-1804
    steps:
      - checkout
      - run:
          name: "build carta_backend"
          command: |
            git submodule update --init --recursive && mkdir build && cd build && cmake .. -Dtest=on && make -j$(nproc)
      - run:
          name: "run unit tests"
          command: |
            cd /root/project/build/test && ./carta_backend_tests --gtest_output=xml --gtest_filter=-"TimerTest*"
      - store_test_results:
            path: /root/project/build/test
workflows:
  build:
    jobs:
      - "format check"
      - "ubuntu bionic"
